### ISSUE TITLE
It cost one minute before returning when the gallery parameter has wrong format

### ISSUE THREAD

**Issue by lubaihua33** [microsoft/lisa#1067]
Here is log:
```
PS C:\xxxx\my_work\lsg-lisa\lisa> poetry run python lisa/main.py -r ..\runbook\smoke.yml -v adminPrivateKeyFile:"C:\xxxx\my_work\lsg-lisa\id_rsa" -v gGallery:"Canonical UbuntuServer 18.04-LTS:Latest"
2020-10-23 09:51:09.714 [INFO] LISA Python version: 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
2020-10-23 09:51:09.715 [INFO] LISA local time: 2020-10-23 17:51:09.715932+08:00
2020-10-23 09:51:09.730 [INFO] LISA run local path: C:\xxxx\my_work\lsg-lisa\lisa\runtime
2020-10-23 09:52:02.723 [INFO] LISA.init[runbook] load runbook from: C:\xxxx\my_work\lsg-lisa\lisa\..\runbook\smoke.yml
2020-10-23 09:52:02.778 [INFO] LISA.init[module] loading extension from C:\xxxx\my_work\lsg-lisa\lisa\..\runbook\..\lisa\testsuites\basic
2020-10-23 09:52:02.813 [INFO] LISA.init[test] registered test suite 'Provisioning' with test cases: 'smoke_test'
2020-10-23 09:52:02.922 [INFO] LISA.init[runbook] run name is 'lisa_Azure fleet smoke_20201023-095109-700'
2020-10-23 09:52:02.928 [INFO] LISA.init[selector] selected count: 1
2020-10-23 09:52:02.929 [INFO] LISA.init[selector] Provisioning.smoke_test, area: provisioning, category: functional, tags: [], priority: 0
2020-10-23 09:52:02.941 [INFO] LISA.init[platform] activated platform 'azure'
2020-10-23 09:52:06.299 [INFO] LISA.[azure] connected to subscription: 'LSG Dev & Test'
2020-10-23 09:52:10.234 [INFO] LISA completed in 60.534 sec
2020-10-23 09:52:10.236 [ERROR] LISA Invalid value for the provided gallery parameter: 'Canonical UbuntuServer 18.04-LTS:Latest'.The gallery parameter should be in the format: '<Publisher> <Offer> <Sku> <Version>'
Traceback (most recent call last):
  File "lisa/main.py", line 71, in <module>
    exit_code = main()
  File "lisa/main.py", line 60, in main
    exit_code = args.func(args)
  File "C:\xxxx\my_work\lsg-lisa\lisa\lisa\commands.py", line 37, in run
    asyncio.run(awaitable)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\xxxx\my_work\lsg-lisa\lisa\lisa\lisarunner.py", line 51, in start
    prepared_environments = platform.prepare_environments(candidate_environments)
  File "C:\xxxx\my_work\lsg-lisa\lisa\lisa\platform_.py", line 81, in prepare_environments
    is_success = self._prepare_environment(environment, log)
  File "C:\xxxx\my_work\lsg-lisa\lisa\lisa\sut_orchestrator\azure\platform_.py", line 296, in _prepare_environment
    node_runbook: AzureNodeSchema = req.get_extended_runbook(
  File "C:\xxxx\my_work\lsg-lisa\lisa\lisa\schema.py", line 128, in get_extended_runbook
    self._extended_runbook: T = runbook_type.schema().load(  # type:ignore
  File "C:\Users\balu\AppData\Local\pypoetry\Cache\virtualenvs\lisa-uBE6sJ2b-py3.8\lib\site-packages\marshmallow\schema.py", line 723, in load
    return self._do_load(
  File "C:\Users\balu\AppData\Local\pypoetry\Cache\virtualenvs\lisa-uBE6sJ2b-py3.8\lib\site-packages\marshmallow\schema.py", line 893, in _do_load
    result = self._invoke_load_processors(
  File "C:\Users\balu\AppData\Local\pypoetry\Cache\virtualenvs\lisa-uBE6sJ2b-py3.8\lib\site-packages\marshmallow\schema.py", line 1091, in _invoke_load_processors
    data = self._invoke_processors(
  File "C:\Users\balu\AppData\Local\pypoetry\Cache\virtualenvs\lisa-uBE6sJ2b-py3.8\lib\site-packages\marshmallow\schema.py", line 1223, in _invoke_processors
    data = processor(data, many=many, **kwargs)
  File "C:\Users\balu\AppData\Local\pypoetry\Cache\virtualenvs\lisa-uBE6sJ2b-py3.8\lib\site-packages\dataclasses_json\mm.py", line 334, in make_instance
    return _decode_dataclass(cls, kvs, partial)
  File "C:\Users\balu\AppData\Local\pypoetry\Cache\virtualenvs\lisa-uBE6sJ2b-py3.8\lib\site-packages\dataclasses_json\core.py", line 208, in _decode_dataclass
    return cls(**init_kwargs)
  File "<string>", line 9, in __init__
  File "C:\xxxx\my_work\lsg-lisa\lisa\lisa\sut_orchestrator\azure\platform_.py", line 134, in __post_init__
    raise LisaException(
lisa.util.LisaException: Invalid value for the provided gallery parameter: 'Canonical UbuntuServer 18.04-LTS:Latest'.The gallery parameter should be in the format: '<Publisher> <Offer> <Sku> <Version>'
PS C:\xxxx\my_work\lsg-lisa\lisa>
```

**Comment by squirrelsc** [comment]
@lubaihua33 can you include debug level logs also?

**Comment by lubaihua33** [comment]
> @lubaihua33 can you include debug level logs also?

@squirrelsc I could not repro this issue in my local environment. I guess this may have a relationship with updated some python packages. Now It cost 10 seconds to return in my local environment. I think it's great.

**Comment by squirrelsc** [comment]
I see, it may related to download cache for location capabilities. I will close this as not repro. Baihua, thank you for confirming.
