### ISSUE TITLE
dependencies are incorrect for ubuntu 18.04

### ISSUE THREAD

**Issue by mcgov** [microsoft/lisa#1271]
Documentation steps to set up an ubuntu VM aren't valid (anymore? I think they worked as recently as last week).
```

mamcgove@mamcgove-ubuntu-test:~/lisa$ curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python3.8 -
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

/home/mamcgove/.local/bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.1.5): Creating environment
Traceback (most recent call last):
  File "<stdin>", line 808, in <module>
  File "<stdin>", line 804, in main
  File "<stdin>", line 417, in run
  File "<stdin>", line 439, in install
  File "<stdin>", line 503, in make_env
ModuleNotFoundError: No module named 'virtualenv'
mamcgove@mamcgove-ubuntu-test:~/lisa$ history
    1  sudo apt update
    2  sudo apt install software-properties-common -y
    3  sudo add-apt-repository ppa:deadsnakes/ppa -y
    4  sudo apt install python3.8 -y
    5  sudo apt install git gcc libgirepository1.0-dev libcairo2-dev
    6  git clone https://github.com/microsoft/lisa.git
    7  cd lisa
    8  git checkout main
    9  curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python3 -

```

**Comment by mcgov** [comment]
`sudo apt install virtualenv` installs a version which is too old.
`sudo apt install python3-pip && pip3 install virtualenv` installs a version >20, which will satisfy the requirement for a compatible version.
