### ISSUE TITLE
Installation instructions should be updated

### ISSUE THREAD

**Issue by praveen-pk** [microsoft/lisa#1308]
While following the instructions to install lisa, I ran into the following error:

```
# curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python3 -
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

/root/.local/bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.1.6): Creating environment
Traceback (most recent call last):
  File "<stdin>", line 808, in <module>
  File "<stdin>", line 804, in main
  File "<stdin>", line 417, in run
  File "<stdin>", line 439, in install
  File "<stdin>", line 503, in make_env
ModuleNotFoundError: No module named 'virtualenv'

```

poetry has a dependency on virtualenv which is not captured in the documentation.

**Comment by squirrelsc** [comment]
@praveen-pk Can you share what distro are you using?

**Comment by glima** [comment]
Our notes on that seem a little bit dated, since only the curl call does all you need these days, apparently. Also, very dangerous to trust those curl calls on a non-priviledged shell, why are you doing things as root here?

**Comment by praveen-pk** [comment]
```
# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.10 (Groovy Gorilla)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.10"
VERSION_ID="20.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
```

I am running the instructions on a container for sanity check. I will setup my env as a non-root user once I figure out working instructions.

**Comment by squirrelsc** [comment]
Thank you point out it. Will fix the installation scripts.
