### ISSUE TITLE
Kernel version parsing dies on RHEL 7

### ISSUE THREAD

**Issue by mcgov** [microsoft/lisa#1497]
From a run using "marketplace_image:RedHat RHEL 7-RAW latest" 

```
lisa.env[generated_0].node[0].cmd[5907] not found command: Command not found: waagent. 
Check that waagent is installed and on $PATH
2021-08-25 23:02:03.525[26188][ERROR] lisa.env[generated_0] failed to get environment information

Traceback (most recent call last):

  File "G:\lisadpdk\lisa\environment.py", line 458, in get_environment_information
    linux_information = uname.get_linux_information()
  File "G:\lisadpdk\lisa\base_tools\uname.py", line 59, in get_linux_information
    kernel_version=parse_version(match_result.group("kernel_version")),
  File "G:\lisadpdk\lisa\util\__init__.py", line 315, in parse_version
    ver: Dict[str, Any] = {
  File "G:\lisadpdk\lisa\util\__init__.py", line 316, in <dictcomp>
    key: 0 if value is None else int(value)
ValueError: invalid literal for int() with base 10: '1062.1.1.el7.x86_64'
```

**Comment by mcgov** [comment]
Going to drop the uname -r result here in a second

**Comment by mcgov** [comment]
3.10.0-1062.1.1.el7.x86_64

**Comment by squirrelsc** [comment]
Thank you for reporting, I will look at it.
