### ISSUE TITLE
Feature requirement SRIOV isn't enabling SRIOV

### ISSUE THREAD

**Issue by mcgov** [microsoft/lisa#1501]
Rebased this morning and SRIOV feature isn't working as expected. Running a test with VM Size Standard_DS15_v2:

test case requirement is as follows:
```
 @TestCaseMetadata(
        description="""
            This test case checks DPDK can be built and installed correctly.
        """,
        requirement=simple_requirement(
            supported_features=[Sriov],
        ),
        priority=1,
    )
```

result
```
Traceback (most recent call last):
  File "G:\lisadpdk\lisa\testsuite.py", line 710, in __run_case
    self.__call_with_retry_and_timeout(
  File "G:\lisadpdk\lisa\testsuite.py", line 731, in __call_with_retry_and_timeout
    retry_call(
  File "C:\Users\matth\AppData\Local\pypoetry\Cache\virtualenvs\lisa-nAelX2u6-py3.8\lib\site-packages\retry\api.py", line 101, in retry_call
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter, logger)
  File "C:\Users\matth\AppData\Local\pypoetry\Cache\virtualenvs\lisa-nAelX2u6-py3.8\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "C:\Users\matth\AppData\Local\pypoetry\Cache\virtualenvs\lisa-nAelX2u6-py3.8\lib\site-packages\func_timeout\dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "C:\Users\matth\AppData\Local\pypoetry\Cache\virtualenvs\lisa-nAelX2u6-py3.8\lib\site-packages\func_timeout\py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "G:\lisadpdk\lisa\testsuite.py", line 448, in wrapper
    func(*args, **parameters)
  File "G:\lisadpdk\microsoft\testsuites\dpdk\dpdksuite.py", line 40, in check_dpdk_build
    assert_that(sriov_is_enabled).described_as(
  File "C:\Users\matth\AppData\Local\pypoetry\Cache\virtualenvs\lisa-nAelX2u6-py3.8\lib\site-packages\assertpy\base.py", line 254, in is_true
    self.error('Expected <True>, but was not.')
  File "C:\Users\matth\AppData\Local\pypoetry\Cache\virtualenvs\lisa-nAelX2u6-py3.8\lib\site-packages\assertpy\assertpy.py", line 433, in error
    raise AssertionError(out)
AssertionError: [SRIOV was not enabled for this test node.] Expected <True>, but was not.
```

**Comment by squirrelsc** [comment]
Thanks for reporting, I will fix it.
