### ISSUE TITLE
Failed to run `verify_gpu_cuda_with_pytorch` on `Standard_ND96asr_v4`

### ISSUE THREAD

**Issue by hcoona** [microsoft/lisa#2823]
Related logs:

```
2023-06-27 06:27:41.764[18188][DEBUG] lisa.env[generated_4].node[0].cmd[384].stdout /home/l****t/.local/lib/python3.6/site-packages/torch/cuda/__init__.py:80: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 802: system not yet initialized (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:112.)
2023-06-27 06:27:41.764[18188][DEBUG] lisa.env[generated_4].node[0].cmd[384].stdout   return torch._C._cuda_getDeviceCount() > 0
2023-06-27 06:27:41.764[18188][DEBUG] lisa.env[generated_4].node[0].cmd[384].stdout gpu count: 0
2023-06-27 06:27:41.841[16376][DEBUG] lisa.env[generated_4].node[0].cmd[384] execution time: 1.395 sec, exit code: 0
2023-06-27 06:27:41.903[16768][ERROR] lisa.suite[Gpu].case[verify_gpu_cuda_with_pytorch] case failed
Traceback (most recent call last):
  File "C:\GitEnlistments\github.com\microsoft\lisa\lisa\testsuite.py", line 767, in __run_case
    _call_with_retry_and_timeout(
  File "C:\GitEnlistments\github.com\microsoft\lisa\lisa\testsuite.py", line 63, in _call_with_retry_and_timeout
    retry_call(
  File "C:\Users\shuaizhang\scoop\apps\python\current\Lib\site-packages\retry\api.py", line 101, in retry_call
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter, logger)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shuaizhang\scoop\apps\python\current\Lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
           ^^^
  File "C:\Users\shuaizhang\scoop\apps\python\current\Lib\site-packages\func_timeout\dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "C:\Users\shuaizhang\scoop\apps\python\current\Lib\site-packages\func_timeout\py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "C:\GitEnlistments\github.com\microsoft\lisa\lisa\testsuite.py", line 492, in wrapper
    func(*args, **parameters)
  File "C:\GitEnlistments\github.com\microsoft\lisa\microsoft\testsuites\gpu\gpusuite.py", line 302, in verify_gpu_cuda_with_pytorch
    ).is_greater_than(0)
      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\shuaizhang\scoop\apps\python\current\Lib\site-packages\assertpy\numeric.py", line 224, in is_greater_than
    self.error('Expected <%s> to be greater than <%s>, but was not.' % (self.val, other))
  File "C:\Users\shuaizhang\scoop\apps\python\current\Lib\site-packages\assertpy\assertpy.py", line 433, in error
    raise AssertionError(out)
AssertionError: [GPU must be greater than zero.] Expected <0> to be greater than <0>, but was not.
```

CUDA depends on Fabric Manager, so we got `Error 802: system not yet initialized`. We need to enable service `nvidia-fabricmanager` to finish the initialization.

**Comment by LiliDeng** [comment]
Fix in #2846
