### ISSUE TITLE
DetectDistro in azuremodules.py - Python script fails to run on SLES 12-SP4

### ISSUE THREAD

**Issue by stefanlupsa** [microsoft/lisa#348]
LIS-MODULES-CHECK - python script failed
manual run:
```
lisa@LISAv2-OneVM-v-stlups-YO70-20190620064013-role-0:~> sudo python LIS-MODULES-CHECK.py
2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
Traceback (most recent call last):
  File "LIS-MODULES-CHECK.py", line 78, in <module>
    RunTest("lsmod")
  File "LIS-MODULES-CHECK.py", line 16, in RunTest
    if (DetectDistro()[0] == 'clear-linux-os'):
  File "/home/lisa/azuremodules.py", line 113, in DetectDistro
    version = matchObj.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by stefanlupsa** [comment]
also seen on WALA-VERIFY-HOSTNAME
```
lisa@LISAv2-OneVM-v-stlups-KH89-20190620080843-role-0:~> sudo python WALA-VERIFY-HOSTNAME.py
2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
Traceback (most recent call last):
  File "WALA-VERIFY-HOSTNAME.py", line 49, in <module>
    RunTest(expectedHostname)
  File "WALA-VERIFY-HOSTNAME.py", line 16, in RunTest
    if CheckHostName(expectedHost) and CheckFQDN(expectedHost):
  File "WALA-VERIFY-HOSTNAME.py", line 37, in CheckFQDN
    [current_distro, distro_version] = DetectDistro()
  File "/home/lisa/azuremodules.py", line 113, in DetectDistro
    version = matchObj.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

```

**Comment by stefanlupsa** [comment]
at the same time in the Runtime.log:
```
06/19/2019 08:06:56 AM : INFO : Detecting Distro 
06/19/2019 08:06:56 AM : DEBUG : SUSE Linux Enterprise Server 12 (x86_64)
VERSION = 12
PATCHLEVEL = 4
# This file is deprecated and will be removed in a future service pack or release.
# Please check /etc/os-release for details about this release.
NAME="SLES"
VERSION="12-SP4"
VERSION_ID="12.4"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP4"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp4"

```

**Comment by LiliDeng** [comment]
#399 fix this issue.
```
[LISAv2 Test Results Summary]
Test Run On           : 07/05/2019 07:44:26
ARM Image Under Test  : SUSE : SLES : 12-SP4 : Latest
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:6

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 CORE                 LIS-MODULES-CHECK                                                                 PASS                 1.93 
 ```
