### ISSUE TITLE
VERIFY-LINUX-DISK-SETUP - RedHat RHEL 7-LVM 7.6.2019060521

### ISSUE THREAD

**Issue by LiliDeng** [microsoft/lisa#361]
No UUID filter from dmesg
```
 python VERIFY-LINUX-DISK-SETUP.py
2.7.5 (default, May 20 2019, 12:21:26)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Traceback (most recent call last):
  File "VERIFY-LINUX-DISK-SETUP.py", line 194, in <module>
    RunTest()
  File "VERIFY-LINUX-DISK-SETUP.py", line 183, in RunTest
    VerifyUUID()
  File "VERIFY-LINUX-DISK-SETUP.py", line 102, in VerifyUUID
    uuid_from_demesg = uuid_from_demesg.replace("\\x2d", "-")
AttributeError: 'int' object has no attribute 'replace'
```

**Comment by LiliDeng** [comment]
@v-sijliu Please take over this.
